#ifndef HELLO_MICHAEL_H
#define HELLO_MICHAEL_H

#define HELLO_MICHAEL_REV_MAJOR 2
#define HELLO_MICHAEL_REV_MINOR 0


/* Some cross-platform definitions generated by autotools */
#if HAVE_CONFIG_H
#  include <config.h>
#endif /* HAVE_CONFIG_H */


#endif /* HELLO_MICHAEL_H */
